apiVersion: v2
appVersion: 0.7.1
description: A Helm chart for RADAR-base oura connector. This application collects data from participants via the Oura Web API.
name: radar-oura-connector
version: 0.5.0
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-oura-connector
- https://github.com/RADAR-base/RADAR-REST-Connector
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: pauline.conde@kcl.ac.uk
    name: Pauline Conde
    url: https://www.kcl.ac.uk/people/pauline-conde
  - email: yatharth.ranjan@kcl.ac.uk
    name: Yatharth Ranjan
    url: https://www.kcl.ac.uk/people/yatharth-ranjan
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
