apiVersion: v2
name: radar-cloudnative-timescaledb
version: 0.2.1
description: CloudNativePG TimescaleDB cluster helm chart for RADAR-base
home: https://radar-base.org
icon: http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-cloudnative-timescaledb
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
- name: cluster
  repository: file://../../external/cloudnativepg-cluster
  version: 0.3.1
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
