apiVersion: v2
appVersion: "v1.3.0"
description: A ORY Kratos Helm chart for RADAR-base. ORY Kratos is a cloud native Identity and User Management system.
name: radar-kratos
home: https://radar-base.org
icon: http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-kratos
version: 0.1.1
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
type: application
dependencies:
- name: kratos
  version: 0.52.1
  repository: file://../../external/kratos
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
