apiVersion: v2
appVersion: "10.5.2"
name: radar-jdbc-connector
description: A Helm chart for RADAR-base JDBC Kafka connector. This is a fork of the Kafka JDBC connector which allows data from topics to be imported into JDBC databases (including TimescaleDB databases which is used in the dashboard pipeline).
version: 0.5.1
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-jdbc-connector
- https://github.com/RADAR-base/RADAR-JDBC-Connector
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: pauline.conde@kcl.ac.uk
    name: Pauline Conde
    url: https://www.kcl.ac.uk/people/pauline-conde
  - email: keyvan@thehyve.nl
    name: Keyvan Hedayati
    url: https://www.thehyve.nl
  - email: joris@thehyve.nl
    name: Joris Borgdorff
    url: https://www.thehyve.nl/experts/joris-borgdorff
  - email: nivethika@thehyve.nl
    name: Nivethika Mahasivam
    url: https://www.thehyve.nl/experts/nivethika-mahasivam
