{{- $root := . -}}
{{- range $name, $svc := $root.Values.services }}
{{- if and $svc.enabled $svc.networkpolicy }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ include "appserver-microservices.serviceFullname" ( dict "root" $root "serviceName" $name ) }}
  namespace: {{ include "common.names.namespace" $root | quote }}
  labels: {{- include "appserver-microservices.labels" ( dict "root" $root "serviceName" $name ) | nindent 4 }}
  {{- if $root.Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $root.Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
{{ include "appserver-microservices.labels" ( dict "root" $root "serviceName" $name ) | indent 6 }}
{{- tpl (toYaml $svc.networkpolicy) .  | nindent 2 }}
---
{{- end }}
{{- end }}
