{{- $root := . -}}
{{- range $name, $svc := $root.Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appserver-microservices.serviceFullname" ( dict "root" $root "serviceName" $name ) }}
  namespace: {{ include "common.names.namespace" $root | quote }}
  labels: {{- include "appserver-microservices.labels" ( dict "root" $root "serviceName" $name ) | nindent 4 }}
  {{- if $root.Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $root.Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not $svc.postgres.urlSecret }}
  {{- $port := $svc.postgres.port | default "5432" }}
  {{- $url := printf "jdbc:postgresql://%s:%s/%s" $svc.postgres.host $port $svc.postgres.database }}
  {{- if $svc.postgres.connection_parameters }}
  databaseUrl: {{ printf "%s?%s" $url $svc.postgres.connection_parameters | b64enc | quote }}
  {{- else }}
  databaseUrl: {{ $url | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not $svc.postgres.userSecret }}
  databaseUser: {{ $svc.postgres.user | b64enc | quote }}
  {{- end }}
  {{- if not $svc.postgres.passwordSecret }}
  databasePassword: {{ $svc.postgres.password | b64enc | quote }}
  {{- end }}
  githubClientToken: {{ $svc.github_client_token | b64enc | quote }}
  firebaseAdminSdkKey: {{ $svc.google_application_credentials | b64enc | quote }}
  {{- if and $svc.smtp.enabled $svc.smtp.auth }}
  smtpUsername: {{ $svc.smtp.username | b64enc | quote }}
  smtpPassword: {{ $svc.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if and $svc.upload.enabled (eq $svc.upload.storage.type "s3") }}
  s3AccessKey: {{ $svc.upload.storage.access_key | b64enc | quote }}
  s3SecretKey: {{ $svc.upload.storage.secret_key | b64enc | quote }}
{{- end }}
---
{{- end }}
{{- end }}
