{{- $root := . -}}
{{- range $name, $svc := $root.Values.services }}
{{- if $svc.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "appserver-microservices.serviceFullname" ( dict "root" $root "serviceName" $name ) }}
  namespace: {{ include "common.names.namespace" $root | quote }}
  labels: {{- include "appserver-microservices.labels" ( dict "root" $root "serviceName" $name ) | nindent 4 }}
  {{- if $root.Values.global.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $root.Values.global.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.service.type }}
  ports:
    - port: {{ $svc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list $svc.podLabels $svc.commonLabels ) "context" . ) }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $root ) | nindent 4 }}
---
{{- end }}
{{- end }}
