apiVersion: v2
appVersion: 0.8.0
description: A subproject of Apache NiFi to store and manage shared resources.
home: https://github.com/dysnix/charts/tree/master/dysnix/nifi-registry
icon: https://svn.apache.org/repos/asf/nifi/site/trunk/images/niFi-logo-horizontal-scaled.png
maintainers:
- email: daniel@dysnix.com
  name: daniel-yavorovich
name: nifi-registry
type: application
version: 1.0.0
