apiVersion: v2
appVersion: "0.2.2"
description: A Helm chart for RADAR-base Push Endpoint. REST Gateway to Kafka, for incoming data from Push or Subscription based WEB APIs. It performs authentication, authorization and content validation. For more details of the configurations, see https://github.com/RADAR-base/RADAR-PushEndpoint.
name: radar-push-endpoint
version: 0.2.4
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-push-endpoint
- https://github.com/RADAR-base/RADAR-PushEndpoint
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: yatharth.ranjan@kcl.ac.uk
    name: Yatharth Ranjan
    url: https://www.kcl.ac.uk/people/yatharth-ranjan
  - email: pauline.conde@kcl.ac.uk
    name: Pauline Conde
    url: https://www.kcl.ac.uk/people/pauline-conde
