apiVersion: v2
appVersion: "0.6.4"
description: A Helm chart for RADAR-base upload connector frontend application that provides a UI for uploading files and sending them to the upload-backend.
name: radar-upload-connect-frontend
version: 0.8.1
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-upload-connect-frontend
- https://github.com/RADAR-base/radar-upload-source-connector
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
