apiVersion: v2
appVersion: 1.0.0
description: A Helm chart for Airflow used by RADAR-base
name: radar-airflow
version: 0.1.0
home: https://radar-base.org
icon: http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-airflow
type: application
maintainers:
  - email: heet.sankesara@kcl.ac.uk
    name: Heet Sankesara
    url: https://phidatalab.org/team/heet-sankesara/
dependencies:
- name: airflow
  version: 1.18.0
  repository: file://../../external/airflow
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
