apiVersion: v2
appVersion: "0.0.1"
description: A Helm chart for RADAR-base Self Enrolment UI
name: radar-self-enrolment-ui
version: 0.2.3
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-self-enrolment-ui
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
type: application
home: "https://radar-base.org"
maintainers:
  - email: yatharth.ranjan@kcl.ac.uk
    name: Yatharth Ranjan
    url: https://www.kcl.ac.uk/people/yatharth-ranjan
  - email: pauline.conde@kcl.ac.uk
    name: Pauline Conde
    url: https://www.kcl.ac.uk/people/pauline-conde
dependencies:
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
