apiVersion: v1
kind: Secret
metadata:
  name: nifi-config-secrets
  namespace: default
  labels:
    {{- include "radar-nifi.labels" . | nindent 4 }}
type: Opaque
stringData:
# Toyaml
  nifi-config-secrets: |
    {{- range $key, $value := index .Values "nifi-config-secrets" }}
    {{ $key }}={{ $value }}
    {{- end }}
