{{- if index .Values "nifi-cluster" "cluster" "singleUserConfiguration" "enabled" }}
apiVersion: v1
kind: Secret
metadata:
  name: nifi-single-user-credentials
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.auth.singleUser.username | b64enc | quote }}
  password: {{ .Values.auth.singleUser.password | b64enc | quote }}
{{- end }}
