apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if not .Values.postgres.urlSecret }}
  {{- $port := .Values.postgres.port | default "5432" }}
  {{- $url := printf "jdbc:postgresql://%s:%s/%s" .Values.postgres.host $port .Values.postgres.database }}
  {{- if .Values.postgres.connection_parameters }}
  databaseUrl: {{ printf "%s?%s" $url .Values.postgres.connection_parameters | b64enc | quote }}
  {{- else }}
  databaseUrl: {{ $url | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if not .Values.postgres.userSecret }}
  databaseUser: {{ .Values.postgres.user | b64enc | quote }}
  {{- end }}
  {{- if not .Values.postgres.passwordSecret }}
  databasePassword: {{ .Values.postgres.password | b64enc | quote }}
  {{- end }}
  githubClientToken: {{ .Values.github_client_token | b64enc | quote }}
  firebaseAdminSdkKey: {{ .Values.google_application_credentials | b64enc | quote }}
  {{- if and .Values.smtp.enabled .Values.smtp.auth }}
  smtpUsername: {{ .Values.smtp.username | b64enc | quote }}
  smtpPassword: {{ .Values.smtp.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.upload.enabled (eq .Values.upload.storage.type "s3") }}
  s3AccessKey: {{ .Values.upload.storage.access_key | b64enc | quote }}
  s3SecretKey: {{ .Values.upload.storage.secret_key | b64enc | quote }}
{{- end }}
