apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-s3-config
  labels: {{ include "common.labels.standard" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  s3_config.json: {{ include "radar-seaweedfs.write-config" . | b64enc | quote }}
