apiVersion: v2
appVersion: 3.9.0
description: A Helm chart for RADAR-base fitbit Kafka connector using the Strimzi Operator. This application collects data from participants via the Fitbit Web API.
name: radar-fitbit-connector-strimzi
version: 0.0.2
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-fitbit-connector-strimzi
- https://github.com/RADAR-base/RADAR-REST-Connector
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
