apiVersion: v2
name: radar-timescaledb
version: 0.1.0
appVersion: latest-pg12-bitnami
description: TimescaleDB is an open-source time-series database optimized for fast ingest and complex queries, built as
  an extension to PostgreSQL. It leverages PostgreSQL's reliability and ecosystem while adding time-series specific
  optimizations and features, such as automatic partitioning and compression.
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
  - name: postgresql
    version: 12.1.9
    repository: file://../../external/postgresql
