apiVersion: v2
name: radar-console
version: 0.0.1
appVersion: "0.0.1"
description: A Helm chart for the frontend application of RADAR-base console application.
type: application
home: "https://radar-base.org"
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-console
- https://github.com/RADAR-base/radar-app-config
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
dependencies:
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
- name: helmet
  version: 0.14.0
  repository: https://charts.companyinfo.dev
  import-values:
    - defaults
