apiVersion: v2
appVersion: "0.4.1"
description: A Helm chart for RADAR-base fitbit connector. This application collects data from participants via the Fitbit Web API.
name: radar-fitbit-connector
version: 0.2.5
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-fitbit-connector
- https://github.com/RADAR-base/RADAR-REST-Connector
keywords:
  - radar-base
  - remote-trial
annotations:
  artifacthub.io/license: Apache-2.0
deprecated: false
type: application
home: "https://radar-base.org"
maintainers:
  - email: keyvan@thehyve.nl
    name: Keyvan Hedayati
    url: https://www.thehyve.nl
  - email: joris@thehyve.nl
    name: Joris Borgdorff
    url: https://www.thehyve.nl/experts/joris-borgdorff
  - email: nivethika@thehyve.nl
    name: Nivethika Mahasivam
    url: https://www.thehyve.nl/experts/nivethika-mahasivam
