apiVersion: v2
appVersion: "v2.2.0"
description: A ORY Hydra Helm chart for RADAR-base. ORY Hydra is a cloud native Identity and User Management system.
name: hydra
home: https://radar-base.org
icon: http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png
sources:
- https://github.com/RADAR-base/radar-helm-charts/tree/main/charts/radar-hydra
version: 0.2.2
maintainers:
  - email: pim@thehyve.nl
    name: Pim van Nierop
    url: https://www.thehyve.nl/experts/pim-van-nierop
type: application
dependencies:
- name: hydra
  version: 0.53.0
  repository: file://../../external/hydra
- name: common
  repository: https://radar-base.github.io/radar-helm-charts
  tags:
  - bitnami-common
  version: 2.x.x
